# Generated by Django 3.1.13 on 2021-10-04 11:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('course_type', models.CharField(choices=[('Course', 'Course'), ('Bootcamp', 'Bootcamp'), ('Event', 'Event')], default='Course', max_length=25)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Video', 'Video'), ('Event', 'Event'), ('Text', 'Text'), ('Quiz', 'Quiz')], max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration', models.CharField(max_length=100)),
                ('forum_url', models.URLField(blank=True, null=True)),
                ('video_youtube_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Content Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('op4', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.quiz')),
            ],
        ),
    ]
