# Generated by Django 3.2.10 on 2022-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220121_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='event_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
