# Generated by Django 3.2.10 on 2022-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='multi_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
