# Generated by Django 3.2.10 on 2023-09-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_course_multi_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_comebackjourney',
            field=models.BooleanField(default=False),
        ),
    ]
