# Generated by Django 3.2.10 on 2023-10-27 12:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_course_is_comebackjourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detailed_desc',
            field=tinymce.models.HTMLField(default='', verbose_name='Detailed Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='preview_youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube Preview ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='testimonials',
            field=tinymce.models.HTMLField(default='', verbose_name='Testimonials'),
            preserve_default=False,
        ),
    ]
