# Generated by Django 3.2.10 on 2023-11-03 11:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20231027_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detailed_desc',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='testimonials',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Testimonials'),
        ),
    ]
