# Generated by Django 3.2.10 on 2022-02-09 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_event_datetime'),
        ('pages', '0002_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='content.course')),
            ],
        ),
    ]
