# Generated by Django 3.2.10 on 2022-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_promotedcourses_promotedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedcourse',
            name='name',
            field=models.CharField(default='initial', max_length=100),
            preserve_default=False,
        ),
    ]
