# Generated by Django 3.2.10 on 2022-02-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_event_datetime'),
        ('pages', '0005_promotedcourse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedcourse',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.course'),
        ),
    ]
