# Generated by Django 3.2.10 on 2022-05-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='https://ibupunyamimpi.org/'),
            preserve_default=False,
        ),
    ]
