# Generated by Django 3.2.10 on 2023-09-12 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_course_is_comebackjourney'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComebackJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('weeks', models.PositiveIntegerField()),
                ('cohort_size', models.PositiveIntegerField()),
                ('remaining_spots', models.PositiveIntegerField()),
                ('signup_start_date', models.DateField()),
                ('signup_end_date', models.DateField()),
                ('course_start_date', models.DateField()),
                ('one_time_price', models.PositiveBigIntegerField()),
                ('monthly_price', models.PositiveBigIntegerField()),
                ('num_monthly_pmts', models.PositiveIntegerField()),
                ('internal_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(related_name='comeback_journeys', to='content.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ComebackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('is_monthly_pmt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('one_time_price', models.PositiveBigIntegerField()),
                ('monthly_price', models.PositiveBigIntegerField()),
                ('num_monthly_pmts', models.PositiveIntegerField(default=0)),
                ('pmts_completed', models.PositiveIntegerField(default=0)),
                ('internal_notes', models.TextField(blank=True)),
                ('comeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comeback_records', to='comeback.comebackjourney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comeback_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comeback')},
            },
        ),
    ]
