# Generated by Django 3.2.10 on 2023-09-01 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comebackjourney',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='comebackjourney',
            name='start_date',
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='cohort_size',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='course_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='internal_notes',
            field=models.TextField(default='notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='monthly_price',
            field=models.PositiveBigIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='num_monthly_pmts',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='one_time_price',
            field=models.PositiveBigIntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='remaining_spots',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='signup_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='weeks',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
