# Generated by Django 3.2.10 on 2023-09-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comebackjourney',
            name='slug',
        ),
    ]
