# Generated by Django 3.2.10 on 2023-09-01 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0002_auto_20230901_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='comebackjourney',
            name='signup_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comebackjourney',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
