# Generated by Django 3.2.10 on 2023-09-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0002_remove_comebackjourney_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comebackjourney',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
