# Generated by Django 3.2.10 on 2023-09-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0003_comebackjourney_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComebackWaitlist',
        ),
    ]
