# Generated by Django 3.2.10 on 2023-09-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0003_auto_20230901_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comebackjourney',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
