# Generated by Django 3.2.10 on 2023-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0003_comebackwaitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comebackjourney',
            name='remaining_spots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
