# Generated by Django 3.2.10 on 2023-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_course_is_comebackjourney'),
        ('comeback', '0004_alter_comebackjourney_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comebackjourney',
            name='courses',
            field=models.ManyToManyField(related_name='comeback_journeys', to='content.Course'),
        ),
    ]
