# Generated by Django 3.2.10 on 2023-09-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0004_alter_comebackjourney_remaining_spots'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='comebackrecord',
        #     unique_together=set(),
        # ),
        migrations.RemoveField(
            model_name='comebackrecord',
            name='comeback',
        ),
    ]
