# Generated by Django 3.2.10 on 2023-09-18 12:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0005_comebackwaitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comebackjourney',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
