# Generated by Django 3.2.10 on 2023-09-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0005_auto_20230917_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='comebackrecord',
            name='comeback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comeback_records', to='comeback.comebackjourney'),
            preserve_default=False,
        ),
    ]
