# Generated by Django 3.2.10 on 2022-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseemail',
            name='send_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupemail',
            name='send_now',
            field=models.BooleanField(default=False),
        ),
    ]
