# Generated by Django 3.2.10 on 2022-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20220317_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseemail',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupemail',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=100),
            preserve_default=False,
        ),
    ]
