# Generated by Django 3.2.10 on 2022-05-30 15:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20220317_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseemail',
            name='text_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='groupemail',
            name='text_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
