# Generated by Django 3.2.10 on 2023-09-18 14:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0006_alter_comebackjourney_description'),
        ('emails', '0004_auto_20220530_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComebackWaitlistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text_content', tinymce.models.HTMLField()),
                ('send_now', models.BooleanField(default=False)),
                ('waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='comeback.comebackwaitlist')),
            ],
        ),
        migrations.CreateModel(
            name='ComebackJourneyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text_content', tinymce.models.HTMLField()),
                ('send_now', models.BooleanField(default=False)),
                ('comeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='comeback.comebackjourney')),
            ],
        ),
    ]
