# Generated by Django 3.2.10 on 2023-09-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_comebackjourneyemail_comebackwaitlistemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comebackwaitlistemail',
            name='waitlist',
        ),
    ]
