# Generated by Django 3.2.10 on 2022-02-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=-9999, max_length=30),
            preserve_default=False,
        ),
    ]
