# Generated by Django 3.2.10 on 2022-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220121_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('FlipID', 'FlipID'), ('Xendit', 'Xendit'), ('Bank Transfer', 'Bank Transfer'), ('Payment Code', 'Payment Code')], max_length=20),
        ),
    ]
