# Generated by Django 3.2.10 on 2022-02-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_course_event_datetime'),
        ('order', '0004_auto_20220125_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.PositiveIntegerField()),
                ('remaining_coupons', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_coupons', to='content.course')),
            ],
        ),
    ]
