# Generated by Django 3.2.10 on 2022-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220209_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
