# Generated by Django 3.2.10 on 2022-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='tickets',
            field=models.IntegerField(default=1),
        ),
    ]
