# Generated by Django 3.2.10 on 2023-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_courserecord_tickets'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursecoupon',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_code'),
        ),
    ]
