# Generated by Django 3.2.10 on 2023-09-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0001_initial'),
        ('content', '0005_course_is_comebackjourney'),
        ('order', '0009_coursecoupon_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='comeback_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_records', to='comeback.comebackrecord'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comeback_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_comeback', to='comeback.comebackrecord'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='content.course'),
        ),
    ]
