# Generated by Django 3.2.10 on 2023-09-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0001_initial'),
        ('order', '0010_auto_20230912_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='comeback_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_comeback', to='comeback.comebackrecord'),
        ),
    ]
