# Generated by Django 3.2.10 on 2023-09-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comeback', '0001_initial'),
        ('order', '0011_alter_orderitem_comeback_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='comeback_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_records', to='comeback.comebackrecord'),
        ),
    ]
